-- Desktop 3 monitors configuration
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
hl.monitor({
	output = "DP-1",
	mode = "2560x1440@143.86",
	position = "2560x0",
	scale = "1",
})

hl.monitor({
	output = "DP-2",
	mode = "2560x1440@74.92",
	position = "5120x0",
	scale = "1",
})

hl.monitor({
	output = "DP-3",
	mode = "2560x1440@74.92",
	position = "0x0",
	scale = "1",
})

-- Per-monitor workspace blocks: each screen owns its own 1-10. Safe here
-- because the monitor set is fixed, so a block can never be orphaned by a
-- screen going away. keybindings.lua picks its dispatchers off this require.
local hs = require("hyprsplit")
hs.config({ num_workspaces = 10 })
-- physical left-to-right; reorder to change which monitor gets 1-10
hs.monitor_priority({ "DP-3", "DP-1", "DP-2" })
